-- 코드를 입력하세요

SELECT *
FROM (
    SELECT INS.NAME NAME, INS.DATETIME DATETIME
    FROM ANIMAL_INS INS
    LEFT JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE OUTS.ANIMAL_ID IS NULL 
    ORDER BY INS.DATETIME
    )
WHERE ROWNUM < 4
