-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
FROM
    (
    SELECT MEMBER_ID
    FROM
        (
        SELECT RR.MEMBER_ID AS MEMBER_ID, COUNT(*) AS NUM
        FROM REST_REVIEW RR
        GROUP BY RR.MEMBER_ID
        ORDER BY NUM DESC
        ) 
    WHERE ROWNUM =1
    ) T1, MEMBER_PROFILE MP, REST_REVIEW RR
WHERE 
MP.MEMBER_ID = T1.MEMBER_ID
AND
T1.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT


