-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE TO_CHAR(BS.SALES_DATE, 'yyyy') = '2022' AND TO_CHAR(BS.SALES_DATE, 'mm') = '01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY